### ISSUE TITLE
A bit more text about Singularity?

### ISSUE THREAD

**Issue by justbennet** [bids-apps/bids-apps.github.io#1]
I had a some bit of trouble with figuring out the appropriate paths that would be available to the Singularity container.  Do you think that adding a bit more text after the example to explain that, when running the Singularity container version, the paths to the data and the output need to be determined specifically for the cluster being used, but that using paths from `/home/` are a good bet?

As you note, different folders will be accessible in different places, and I got confused about which to use.

I can write some text and submit via PR if this seems a good idea.

**Comment by chrisfilo** [comment]
It depends on the particular singularity configuration. /home and /tmp are
good bets. In addition the docker2singularity converter creates mount
points used in Sherlock and XSEEDE clusters

https://github.com/chrisfilo/docker2singularity/blob/master/docker2singularity.sh#L147

We can add the mount points used in your system to the converter.

It would be good to asjust the tutorial http:/   /bit.do/r_testing

**Comment by justbennet** [comment]
The only one we might want is /nfs, which would be where persistent storage
from labs might be kept.  Otherwise, our standard mounts are /home and
/scratch, and I was just able to get /scratch to work.

If it makes a difference, folders under /nfs are handled via autofs on the
host system, I think.  I think you should probably hold off on that until
we have someone who needs it.  There are not a lot of people using the
cluster yet, and there is a layer of support people -- mainly me and Daniel
-- between them and the cluster, so we'll get warning.

-- bennet
