### ISSUE TITLE
Pushing bids app with stable tag

### ISSUE THREAD

**Issue by yeunkim** [bids-apps/bids-apps.github.io#101]
Hi @Remi-Gau 

I made a new release today of BrainSuite BIDS App (with CircleCI tests passed) but I still only see the unstable tag on DockerHub. Could you let me know any additional steps I should take in order to push the "stable" tag version? 

To clarify - I've tried making a git tag (v21a in this case) and pushing the tag with new commits to trigger the circleci tests. I don't know how the $CIRCLE_TAG variable gets set in https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/push_docker.sh. 

Thank you!

**Comment by Remi-Gau** [comment]
let me have a look

**Comment by Remi-Gau** [comment]
Making some notes here:

That script worked a month ago on the base_fsl repo to push a new version on dockerhub.

![Screenshot from 2023-02-15 09-40-32](https://user-images.githubusercontent.com/6961185/218976702-369b3e75-6da2-4e94-868b-f428ad44a8e6.png)

https://app.circleci.com/pipelines/github/bids-apps/base_fsl/27/workflows/2256c7ee-28de-4b96-9a26-132470595b9c/jobs/42?invite=true#step-103-41

I have made some changes to the script but I don't think this is the reason why this did not work in your case.

**Comment by Remi-Gau** [comment]
It seems that when you tagged the project, nothing even happened on the circle-ci side

![Screenshot from 2023-02-15 09-48-13](https://user-images.githubusercontent.com/6961185/218978558-31d5ecf2-295d-4b1e-9b09-fad426c8109a.png)

**Comment by Remi-Gau** [comment]
Add just pushing a new commit will not trigger a new release on docker hub

![Screenshot from 2023-02-15 09-49-49](https://user-images.githubusercontent.com/6961185/218978953-a72860b7-e75c-4a63-878d-d695af38f225.png)

**Comment by Remi-Gau** [comment]
looking at the workflow set up in the circle.ci config it seems that some of your steps are not set to run on tags

what it looks like for brainsuite:

https://github.com/bids-apps/BrainSuite/blob/6efc7a16eb2967dbf2971898916b1518438e2ad8/.circleci/config.yml#L87-L106

what it looks like for base_fsl

https://github.com/bids-apps/base_fsl/blob/2f90c0e137f3d80bcd5b24658ec6cc004fe7db0a/.circleci/config.yml#L33-L51

**Comment by Remi-Gau** [comment]
will try to fix it

**Comment by Remi-Gau** [comment]
- updated the config
- deleted the previous release and tag you did
- made a new one with the same name and tag

looks the workflow is at least running, let's wait and see if the push of the new release happens on dockerhub

https://app.circleci.com/pipelines/github/bids-apps/BrainSuite/58/workflows/5000e07c-c18c-42d9-9c4f-9e73651adee0

**Comment by Remi-Gau** [comment]
Seems to have worked: https://hub.docker.com/layers/bids/brainsuite/v.21a/images/sha256-df3765e0a4b26f837a09c05eeec146d3099b1182975dc2cf1a2483f0bedbb36f?context=explore

**Comment by yeunkim** [comment]
Thanks @Remi-Gau!
