### ISSUE TITLE
failing to get proper github badges on dashboard

### ISSUE THREAD

**Issue by Remi-Gau** [bids-apps/bids-apps.github.io#102]
@sappelhoff 

any idea where this could be coming from?

I have not looked into it yet. Just in case you have a better hunch than me.

![Screenshot from 2023-02-15 15-57-24](https://user-images.githubusercontent.com/6961185/219064200-40b77898-4254-4937-8be7-692fa6489c0a.png)

**Comment by sappelhoff** [comment]
mmh no hunch unfortunately, but we're not the only ones with this issue, see here from 25 minutes ago: https://github.com/badges/shields/issues/7445#issuecomment-1431483707

**Comment by Remi-Gau** [comment]
OK I suspect that smarter people than me are already on this.

**Comment by Remi-Gau** [comment]
seems fixed now
