### ISSUE TITLE
Add fmri data to brainsuite in _config.yml

### ISSUE THREAD

**Issue by yeunkim** [bids-apps/bids-apps.github.io#103]
Hi @Remi-Gau 

Sorry for the barrage of requests. One more thing - could you add "- func" to the datatype in the _config.yml (line 137) for brainsuite? 

- gh: "bids-apps/BrainSuite"
    status: active
    dh: "bids/brainsuite"
    ds_type:
      - raw
    datatype:
      - anat
      - dwi
      - func

Thank you!

**Comment by Remi-Gau** [comment]
If you feel up for it, you can open a pull request. You pretty much have it already figure out in terms of what needs to change.
