### ISSUE TITLE
Add validation that all gh/dh exist as specified in _config.yml

### ISSUE THREAD

**Issue by yarikoptic** [bids-apps/bids-apps.github.io#122]
### Your idea

Inspired by 

- #121

which broke our cron job in https://github.com/ReproNim/containers . So would be nice if _config.yml records were checked for presence on gh/dh.   For dh it is just https://registry.hub.docker.com/v2/repositories/bids/{dh} away AFAIK.

**Comment by Remi-Gau** [comment]
oops sorry about that: I was not aware you were using that yaml file as input

the giga_connectome app pushed on docker hub should be coming soon, hence why I was OK to live with this inconsistency

will adapt the html template to handle missing dh reference

**Comment by Remi-Gau** [comment]
how would your cron job behave if some app had no dh reference?

**Comment by yarikoptic** [comment]
looking at https://github.com/ReproNim/containers/blob/master/scripts/create_singularities#L407 (python code converted from bash ...) it seems we would just skip.
