### ISSUE TITLE
reproa

### ISSUE THREAD

**Issue by tiborauer** [bids-apps/bids-apps.github.io#146]
### Your BIDS app

- gh: "reprostat/reproa"
  dh: "reprostat/reproa"
  branch: "master"
  ds_type:
    - raw
  datatype:
    - anat
    - fmap
    - func

### Submission checklist

- [X] complies to the BIDS app API
- [X] has a system-test workflow set up
- [X] test dataset is validated before processing

**Comment by tiborauer** [comment]
I have modified the test workflow so that the two participants are processed in separate jobs. This solution avoids hitting the 1h timeout. The group-level processing simply processes all participants, which will take more time. I can, however, specify a short, add-data-only workflow just to test this functionality.

**Comment by Remi-Gau** [comment]
added here: https://github.com/bids-apps/bids-apps.github.io/commit/2b0dbae0e1492f60fc7f4eec16a6e13b246645ae

note: this is on the [bfm branch](https://github.com/bids-apps/bids-apps.github.io/tree/bfm) which is used to list the bids apps directly on the new bids website on this page: https://bids-website.readthedocs.io/en/latest/tools/bids-apps.html

**Comment by tiborauer** [comment]
Thank you!
