### ISSUE TITLE
badges not updating

### ISSUE THREAD

**Issue by ccraddock** [BIDS-Apps/bids-apps.github.io#2]
The badges for build success and issue count do not appear to be updating. CPAC now has no issues and several passed circleCI tests, but it still says that its build is a failure and that there is an issue. Do I need to do something to trigger the web page to be rebuilt or something?

**Comment by chrisfilo** [comment]
There is nothing that you need to do. The badges are provided by third
party which might not be as reliable as I had hoped. I'll look into this.
