### ISSUE TITLE
adding new app to the site?

### ISSUE THREAD

**Issue by akhanf** [BIDS-Apps/bids-apps.github.io#32]
Hello! 

I am hoping to have a new app added to the list? Please let me know if there is anything I need do to, it is already set up on circleci.

Docker: khanlab/hippunfold:v0.4.1
Docs: https://hippunfold.readthedocs.io/en/latest/
Github: https://github.com/khanlab/hippunfold

Thanks!
Ali

**Comment by franklin-feingold** [comment]
hi @akhanf 

thank you for your message and interest in submitting a bids-app! If you may please submit a pull request (similar to this one: https://github.com/BIDS-Apps/bids-apps.github.io/pull/29) we can get it incorporated

**Comment by sappelhoff** [comment]
closed by https://github.com/BIDS-Apps/bids-apps.github.io/pull/33
