### ISSUE TITLE
add smriprep and other nipreps to the list

### ISSUE THREAD

**Issue by yarikoptic** [BIDS-Apps/bids-apps.github.io#36]
ref: https://github.com/datalad/datalad-container/issues/157 (attn @m-petersen)

apparently only good old fmriprep is listed

```shell
$> git grep mriprep
_config.yml:  - gh: 'nipreps/fmriprep'
_config.yml:    dh: 'nipreps/fmriprep'
```

and none of the other nipreps bids-apps.  Would be nice to see them added.  context: I use this listing to populate/update (well -- yet to account for shub:// going read-only, so outdated ATM) https://github.com/ReproNim/containers/

**Comment by sappelhoff** [comment]
sure, feel free to do it (maybe tag the devs of those apps), should be as easy as in this PR: https://github.com/BIDS-Apps/bids-apps.github.io/issues/33

**Comment by Remi-Gau** [comment]
Will take care of this
