### ISSUE TITLE
Remove Gemfile.lock?

### ISSUE THREAD

**Issue by sappelhoff** [BIDS-Apps/bids-apps.github.io#45]
I don't we need this file: https://github.com/BIDS-Apps/bids-apps.github.io/blob/c881455dec3cfa966e70b64b8bb8b595d93ca52d/Gemfile.lock#L1

do we? This just contains the "fixed" versions that are to be installed when deploying to GH pages ... but for a simple setup such as this one (or [bids-website](https://github.com/bids-standard/bids-website/)), just the Gemfile should be enough: https://github.com/BIDS-Apps/bids-apps.github.io/blob/c881455dec3cfa966e70b64b8bb8b595d93ca52d/Gemfile#L1

I think that removing the lock file will also get rid of the security warning.

**Comment by Remi-Gau** [comment]
I will remove it. Most likely not needed for something that simple
