### ISSUE TITLE
Rename "BIDS-Apps" org --> "bids-apps" ... capitalization for consistency with bids-standard

### ISSUE THREAD

**Issue by sappelhoff** [bids-apps/bids-apps.github.io#47]
The title says what I'd like to do. What are your opinions? Can you think of potential caveats that we need to check first?

**Comment by Remi-Gau** [comment]
May break some links?

**Comment by sappelhoff** [comment]
yes - according to the docs, the broken links might be minimal (maybe even zero) https://docs.github.com/en/github-ae@latest/organizations/managing-organization-settings/renaming-an-organization

I think it's worth it.

**Comment by Remi-Gau** [comment]
ok with me then

**Comment by sappelhoff** [comment]
Done :-)

This is the stuff that **won't** work anymore:

- https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization#changes-that-occur-automatically
- https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories

in brief:

- the git remotes of local clones need to be updated check `git remote -v`
- links to https://github.com/BIDS-Apps directly don't work (repo and PR/issue links are preserved)
- API requests to https://github.com/BIDS-Apps don't work anymore (use `bids-apps`)
- the `qa` team must from now on be mentioned via `@bids-apps/qa` ... `@BIDS-Apps/qa` does not work anymore

**Comment by Remi-Gau** [comment]
Thanks @sappelhoff
