### ISSUE TITLE
Get rid of superfluous files?

### ISSUE THREAD

**Issue by sappelhoff** [BIDS-Apps/bids-apps.github.io#48]
I think there may be some files in this repository that:

1. either shouldn't be here (there are better places)
2. or are not needed

Candidates for 1.

- [x] `OHBM2017_poster.afdesign` --> this should rather be a PDF on Zenodo or similar
- ...?

Candidates for 2.

- [x] categories.md
- [x] tags.md
- ... ?

Is everyone fine with removing these files? If somebody really needs the poster, it'll be in the git history.

**Comment by Remi-Gau** [comment]
Put the poster on zenodo and link to it. :+1:

Categories and tags: need to test if they are not "needed" when building the website even if we don't use them.

**Comment by sappelhoff** [comment]
just fyi: I am dealing with the poster and will upload it to zenodo soon (using the bids-maintainers GH account)

**Comment by Remi-Gau** [comment]
> just fyi: I am dealing with the poster and will upload it to zenodo soon (using the bids-maintainers GH account)

Awesome! Thanks.
