### ISSUE TITLE
Clarify license and authors

### ISSUE THREAD

**Issue by sappelhoff** [BIDS-Apps/bids-apps.github.io#49]
The license currently says:

https://github.com/BIDS-Apps/bids-apps.github.io/blob/c881455dec3cfa966e70b64b8bb8b595d93ca52d/LICENSE#L3

And the author currently says:

https://github.com/BIDS-Apps/bids-apps.github.io/blob/c881455dec3cfa966e70b64b8bb8b595d93ca52d/_config.yml#L21

I think we should:

1. clarify the role of "Josh Gerdes" ... was he the author of the template used for the website? If yes, we should just make our license more specific: The contents belong to `bids contributors`, the website template belongs to `josh gerdes`
2. Make the "author" (currently Chris G) more inclusive --> this should also be `bids contributors`, given that more people than Chris G have contributed by now (and -- more importantly -- will do so in the future)

What are your opinions?

**Comment by Remi-Gau** [comment]
FYI the author was changed by #42 

https://github.com/BIDS-Apps/bids-apps.github.io/blob/c0e6181c134a5f429b62e58d2c5811a665bbfca5/_config.yml#L24

**Comment by sappelhoff** [comment]
A quick GH search later, one more mystery is solved: Josh Gerdes wrote the Jekyll Template that was used to create this site: https://github.com/joshgerdes/jekyll-uno
