### ISSUE TITLE
Link to BIDS Apps paper, link to "BIDS Apps" BEP027 (aka "BIDS Apps spec"?)

### ISSUE THREAD

**Issue by sappelhoff** [BIDS-Apps/bids-apps.github.io#51]
I didn't find a link to either of those two important resources:

- [x] https://doi.org/10.1371/journal.pcbi.1005209
- [x] https://bids.neuroimaging.io/bep027

**Comment by sappelhoff** [comment]
maybe the paper is already added somewhere though? I see https://github.com/BIDS-Apps/bids-apps.github.io/issues/4

**Comment by Remi-Gau** [comment]
The paper is now linked in the "about" page but we should probably have a useful links section.

The BEP I am planning to mention it in #44 that I need to polish a bit.
