### ISSUE TITLE
Where does the logo come from? -- and: revamping of background image + logo?

### ISSUE THREAD

**Issue by sappelhoff** [bids-apps/bids-apps.github.io#52]
There is currently this logo for the BIDS-Apps organization:

![image](https://user-images.githubusercontent.com/9084751/160091863-843f1f6a-e983-4ad8-aaca-b9aee272dc0a.png)

- https://github.com/BIDS-Apps/bids-apps.github.io/blob/master/images/gear.jpg

I wonder where it comes from, how it is licensed, and whether we should change it to just the BIDS logo.

---

Furthermore, there is currently this background image on the website:

![image](https://user-images.githubusercontent.com/9084751/160091653-55607cdb-a930-44c9-b4b9-53ce2add9d92.png)

- https://github.com/BIDS-Apps/bids-apps.github.io/blob/master/images/cover.jpg

I think we can probably do without it -- it's okay to have it, but it's not really related to "anything BIDS-Apps".

**Comment by Remi-Gau** [comment]
Can try to combine the gear with the BIDS logo to make something more BIDSy... 

The background image I find it soothing and it does not hurt so I'd say until we find something better suited we could keep it.
