### ISSUE TITLE
Make a BIDS-Apps org README

### ISSUE THREAD

**Issue by sappelhoff** [BIDS-Apps/bids-apps.github.io#53]
similar to: https://github.com/bids-standard/

but note #47 (needs to be done first, perhaps)

**Comment by sappelhoff** [comment]
Done, see: https://github.com/BIDS-Apps/

feel free to improve with PRs to https://github.com/BIDS-Apps/.github

I also added a code of conduct (the same one as for bids-standard)

**Comment by Remi-Gau** [comment]
Thanks for taking of this one @sappelhoff
