### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by chrisgorgo** [BIDS-Apps/bids-apps.github.io#6]
Describe how one can contribute to this repository (the bids-apps.neuroimaging.io website)

https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution
https://github.com/emdupre/me-ica/blob/py3/CONTRIBUTING.md

**Comment by hastagAB** [comment]
Hi @chrisgorgo ,
I'd like to add CONTRIBUTING.md for this repo.
Let me know if this issue is still a priority.

**Comment by oesteban** [comment]
I think this would be a great initiative in the context of the Season of Code, @franklin-feingold - WDYT?

That said, @hastagAB all contributions are very welcome. Just wanted to ping Franklin, who is probably the best-indicated person to help you with this.

**Comment by franklin-feingold** [comment]
hi @hastagAB (thanks for ping @oesteban)

Thank you for your interest! Yes please, contributions are very welcome! To give a bit of context - the BIDS-Apps project is currently participating in the [Google Season of Docs](https://neurostars.org/t/bids-apps-google-season-of-docs-information/6999) to primarily build out our documentation for containerizing and running Apps. I think considering how our contributing guide for BIDS-Apps would look like sounds good!

**Comment by hastagAB** [comment]
Hi! 
Sorry for the delay, I didn't get the notification. 
I will start working on this right away and will create a Pull Request when completed.

I'm taking references from these:
1. https://github.com/emdupre/me-ica/blob/py3/CONTRIBUTING.md
2. https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/CONTRIBUTING.md

**Comment by effigies** [comment]
Let's move any further discussion to #26.
