### ISSUE TITLE
A few badges broken

### ISSUE THREAD

**Issue by vsoch** [bids-apps/bids-apps.github.io#66]
Hey BIDS apps team! It looks like a column of badges are 404-ing on https://bids-apps.neuroimaging.io/apps/:

![image](https://user-images.githubusercontent.com/814322/171554027-8e6c6be2-2c6a-447c-a175-e2af8148176c.png)

I suspect a circle workflow was removed, changed, or something along those lines, it looks like the Circle URL that is linked to is 404 along with the badge. https://circleci.com/gh/BIDS-Apps/aa.svg?style=shield

Just wanted to let you know!

**Comment by Remi-Gau** [comment]
thanks @vsoch 

Got a hunch this is related to the renaming of the github organization in https://github.com/bids-apps/bids-apps.github.io/issues/47

@sappelhoff could this be it?

Changing the link manually to use "bids-apps" does not give a 404 but does not give something what we would expect either

https://app.circleci.com/jobs/github/bids-apps/aa/134?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by vsoch** [comment]
That's indeed strange - I can see a workflow run here from about a month ago: https://app.circleci.com/pipelines/github/BIDS-Apps/bids-apps.github.io/27/workflows/d2369073-e132-4a2d-9e08-18fee8035223/jobs/27 but I get 404 clicking up levels to the root of the run. It could be a bug with CircleCI and you could try contacting support?

**Comment by sappelhoff** [comment]
not sure, but 86bb262 might have fixed it? Docker pulls are listed as "invalid" though :thinking: 

![image](https://user-images.githubusercontent.com/9084751/171811052-bcf0a09a-c420-45c1-915f-d7b3e1982f3a.png)

**Comment by sappelhoff** [comment]
This is the problematic badge now ... no idea why though:

https://github.com/bids-apps/bids-apps.github.io/blob/86bb2628c02ec70b1eb3faaadc6249772b6a9902/apps.md?plain=1#L36

**Comment by sappelhoff** [comment]
thanks for your research!

@PeerHerholz and @akhanf did you remove the CircleCI workflow? I am not sure whether the problem is rather with us ... it might be unreasonable to require each BIDS app to have a CircleCI workflow just so that we can conveniently display this on the website :thinking: 

I can look into the renaming ... and regarding "trendscenter/gift-bids", I think there never was a circleci workflow.

**Comment by PeerHerholz** [comment]
Hi folks,

thx for pointing this out and sorry for the late reply, no idea why I missed this.

IIRC I never had a `CircleCI` workflow implemented but a workflow on `Travis` (please see [here](https://travis-ci.org/PeerHerholz/BIDSonym)). However, I can also change/adapt things.

**Comment by sappelhoff** [comment]
no worries @PeerHerholz -- if you could migrate from travis to circleci, that'd be much appreciated as it'd give you the nice badge that we have on the website. But it's certainly not urgent or required.

Alternatively we could / should figure out whether / how we can "customize" the badges we show. E.g., add to each "app" that we list one more metadata item about their main CI flow, and then render a badge based on the status we mine from there. --> this would probably be much superior to asking all app devs to please have a circleci workflow.

**Comment by sappelhoff** [comment]
some more discussion was in https://github.com/bids-apps/bids-apps.github.io/pull/69#discussion_r941542990
