### ISSUE TITLE
logo broken on all but landing page

### ISSUE THREAD

**Issue by PeerHerholz** [bids-apps/bids-apps.github.io#67]
Hi folks,

I just noticed that the `BIDS Apps` logo doesn't show up on all but the landing page. The working logo points to
https://bids-apps.neuroimaging.io/images/BIDS_apps_logo_black.jpg, while the non-working one points to https://bids-apps.neuroimaging.io/dev_faq/images/BIDS_apps_logo_black.jpg. Happy to submit a small PR for this if no one else wants to/is on it.

Cheers, Peer

<img width="1327" alt="Screen Shot 2022-06-21 at 3 58 31 PM" src="https://user-images.githubusercontent.com/20129524/174831725-da93ad04-0c25-4966-b129-666d3a92c330.png">

**Comment by Remi-Gau** [comment]
Thanks for the catch. Yup. Feel free to PR the 💩 out of this.
