### ISSUE TITLE
add BIDS Software Development Guidelines from our google drive?

### ISSUE THREAD

**Issue by Remi-Gau** [bids-apps/bids-apps.github.io#72]
Not sure if this document may be incorporated here on the BIDS apps website or maybe better in the bids starter kit. I cannot decide.

https://docs.google.com/document/d/1_A1GUHAbczHL6WnEw3b8_8_4PXb1A4wZ4Ckrjgapt5c/edit#heading=h.wru3kew0szzp

**Comment by sappelhoff** [comment]
I don't think BIDS APPs would be a good place, because there is lots of BIDS aware software that is not a BIDS App.

Starter kit sounds better, but then again, it's directed more towards users.

Perhaps we can incorporate it somewhere in the BIDS website?

**Comment by sappelhoff** [comment]
update: after discussion with Remi I agree to add it FAQ of the bids-apps website
