### ISSUE TITLE
[BUG] circle ci failures

### ISSUE THREAD

**Issue by Remi-Gau** [bids-apps/bids-apps.github.io#89]
### Describe your problem in detail.

god knows why it cannot checkout the repo...

**Comment by sappelhoff** [comment]
@Remi-Gau I think I just fixed it with the following steps that might also need to be applied to other repos:

1. log into circleci app and select the failing repo
2. click on project settings (upper right)
3. click "SSH keys"
4. remove the deploy key by clicking on the small x (see also screenshot)
5. re-add a new deploy key by adding the button that appears when no deploy keys are present anymore (this gets done automatically, no command-line ssh action required)
6. done

![image](https://user-images.githubusercontent.com/9084751/211292343-fddbba89-c560-45d6-b5d5-68d5e5531af1.png)

**Comment by Remi-Gau** [comment]
thanks for the tip

have not seen this on other repos but good to know if this issuer shows up
